---
title: "Get Started with tidyBdE"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Get Started with tidyBdE}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---



**tidyBdE** is an API package that helps to retrieve data from [Banco de
España](https://www.bde.es/webbde/en/estadis/infoest/descarga_series_temporales.html).
The data is provided as [tibble](https://tibble.tidyverse.org/) and the package
tries to guess the format of every time-series (dates, characters and numbers).

## Search series

Banco de España (**BdE**) provides several time-series, either produced by the
institution itself or compiled for another sources, as
[Eurostat](https://ec.europa.eu/eurostat) or [INE](https://www.ine.es/).

The basic entry point for searching time-series are the catalogs (*indexes*) of
information. You can search any series by name:


```r

library(tidyBdE)

# Load tidyverse for better handling
library(tidyverse)


# Search GBP on "TC" (exchange rate) catalog
XR_GBP <- bde_catalog_search("GBP", catalog = "TC")

XR_GBP %>%
  select(Numero_secuencial, Descripcion_de_la_serie) %>%
  # To table on document
  knitr::kable()
```



| Numero_secuencial|Descripcion_de_la_serie                                            |
|-----------------:|:------------------------------------------------------------------|
|            573214|Tipo de cambio. Libras esterlinas por euro (GBP/EUR).Datos diarios |

**Note that BdE files are only provided in Spanish, for the time being**, the
organism is working on the English version. By now, search terms should be
provided in Spanish in order to get search results.

After we have found our series, we can load the series for the GBP/EUR exchange
rate using the sequential number reference (`Numero_Secuencial`) as:










