---
title: "Main Macroeconomic Series"
output:
  html_document:
    toc: yes
    toc_depth: 2
---

This article shows the evolution of selected economic indicators of 
Spain, based on the information provided by [Banco de España](https://www.bde.es/).

Last update: **`r format(Sys.Date(),"%d-%B-%Y")`**.

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

library(tidyBdE)
library(ggplot2)
library(dplyr)

col <- tidyBdE::bde_rose_pal()(1)
date <- Sys.Date()
ny <- as.numeric(format(date, format = "%Y")) - 4
nd <- as.Date(paste0(ny, "-12-31"))

br <- seq(nd, Sys.Date(), "6 months")
```

## GDP of Spain

### Overall (quarterly values)

```{r echo=FALSE}
dataset <- bde_ind_gdp_var(series_label = "data") %>%
  filter(Date >= nd)

l <- dataset[nrow(dataset), ]

ggplot(dataset, aes(x = Date, y = data)) +
  geom_line(color = col) +
  geom_text(
    data = l,
    size = 3,
    aes(label = paste(x = prettyNum(data, big.mark = " "), "\n", format(Date, "%b-%Y")))
  ) +
  scale_y_continuous(labels = scales::label_number()) +
  labs(
    title = "GDP of Spain",
    subtitle = "million €",
    caption = "Source: BdE"
  ) +
  scale_x_date(
    date_labels = "%b-%Y",
    breaks = br
  ) +
  theme_bde()
```


### GDP by industry (quarterly)

```{r echo=FALSE}
library(tidyr)

dataset_init <- bde_series_load(
  series_code = c(
    3777251,
    3777265,
    3777259,
    3777269,
    3777060
  ),
  series_label = c(
    "Agriculture",
    "Industry",
    "Construction",
    "Services",
    "Total"
  )
) %>%
  filter(Date >= nd)


# Manipulate data - tidyverse style

dataset <- dataset_init %>%
  # Create 'Other' column and convert Date to year
  mutate(
    Other = Total - rowSums(across(Agriculture:Services))
  ) %>%
  select(-Total) %>%
  pivot_longer(Agriculture:Other,
    names_to = "serie",
    values_to = "data"
  )


l <- dataset[nrow(dataset), ]

ggplot(data = dataset, aes(
  x = Date,
  y = data,
  fill = serie
)) +
  geom_bar(
    position = "stack",
    stat = "identity",
    alpha = 0.8
  ) +
  scale_fill_bde_d(palette = "bde_rose_pal") + # Custom palette on the package
  scale_x_date(
    date_labels = "%b-%Y",
    breaks = br
  ) +
  scale_y_continuous(labels = scales::label_number()) +
  theme_bde() +
  labs(
    title = "Spain: Gross domestic product by industry",
    subtitle = "million €",
    caption = "Source: BdE"
  )

rm(list = c("dataset", "dataset_init"))
```

### Year-on-year variation


```{r echo=FALSE}

dataset <- bde_ind_gdp_var(series_label = "data") %>%
  filter(Date >= nd)


l <- dataset[nrow(dataset), ]

ggplot(dataset, aes(x = Date, y = data)) +
  geom_line(color = col) +
  geom_text(
    data = l,
    size = 3,
    aes(label = paste(x = data, "\n", format(Date, "%b-%Y")))
  ) +
  labs(
    title = "GDP of Spain (year-on-year variation)",
    subtitle = "%",
    caption = "Source: BdE"
  ) +
  scale_x_date(
    date_labels = "%b-%Y",
    breaks = br
  ) +
  theme_bde()
```

### GDP per capita

```{r echo=FALSE}

pop <- bde_ind_population(series_label = "pop")
PIB <- bde_ind_gdp_quarterly(series_label = "data")

PIB$LastY <- PIB$data + lag(PIB$data, 1) + lag(PIB$data, 2) + lag(PIB$data, 3)

PIB <- left_join(PIB, pop, by = "Date")

PIB <- PIB %>% mutate(data = 1000 * LastY / pop)

dataset <- PIB %>%
  select(Date, data) %>%
  filter(Date >= nd)


l <- dataset[nrow(dataset), ]

ggplot(dataset, aes(x = Date, y = data)) +
  geom_line(color = col) +
  geom_text(
    data = l,
    size = 3,
    aes(label = paste(x = prettyNum(data, big.mark = " "), "€\n", format(Date, "%b-%Y")))
  ) +
  labs(
    title = "GDP per capita of Spain",
    subtitle = "€",
    caption = "Source: BdE"
  ) +
  scale_y_continuous(labels = scales::label_number()) +
  scale_x_date(
    date_labels = "%b-%Y",
    breaks = br
  ) +
  theme_bde()
```

## Unemployment Rate


```{r echo=FALSE}

dataset <- bde_ind_unemployment_rate(series_label = "data") %>%
  filter(Date >= nd)


l <- dataset[nrow(dataset), ]

ggplot(dataset, aes(x = Date, y = data)) +
  geom_line(color = col) +
  geom_text(
    data = l,
    size = 3,
    aes(label = paste(x = data, "\n", format(Date, "%b-%Y")))
  ) +
  labs(
    title = "Unemployment Rate",
    subtitle = "%",
    caption = "Source: BdE"
  ) +
  scale_x_date(
    date_labels = "%b-%Y",
    breaks = br
  ) +
  theme_bde()
```


## Consumer Price Index


```{r echo=FALSE}

dataset <- bde_ind_cpi_var(series_label = "data") %>%
  filter(Date >= nd)


l <- dataset[nrow(dataset), ]

ggplot(dataset, aes(x = Date, y = data)) +
  geom_line(color = col) +
  geom_text(
    data = l,
    size = 3,
    aes(label = paste(x = data, "\n", format(Date, "%b-%Y")))
  ) +
  labs(
    title = "Consumer Price Index",
    subtitle = "%",
    caption = "Source: BdE"
  ) +
  scale_x_date(
    date_labels = "%b-%Y",
    breaks = br
  ) +
  theme_bde()
```

## Monthly Euribor


```{r echo=FALSE}

dataset <- bde_ind_euribor_12m_monthly(series_label = "data") %>%
  filter(Date >= nd)


l <- dataset[nrow(dataset), ]

ggplot(dataset, aes(x = Date, y = data)) +
  geom_line(color = col) +
  geom_text(
    data = l,
    size = 3,
    aes(label = paste(x = data, "\n", format(Date, "%b-%Y")))
  ) +
  labs(
    title = "Euribor 12 months (monthly)",
    subtitle = "%",
    caption = "Source: BdE"
  ) +
  scale_x_date(
    date_labels = "%b-%Y",
    breaks = br
  ) +
  theme_bde()
```


## Population

```{r echo=FALSE}

dataset <- bde_ind_population(series_label = "data") %>%
  filter(Date >= nd)


l <- dataset[nrow(dataset), ]

ggplot(dataset, aes(x = Date, y = data)) +
  geom_line(color = col) +
  geom_text(
    data = l,
    size = 3,
    aes(label = paste(
      x = prettyNum(data, big.mark = " "),
      "\n", format(Date, "%b-%Y")
    ))
  ) +
  labs(
    title = "Population of Spain",
    subtitle = "thousands",
    caption = "Source: BdE"
  ) +
  scale_x_date(
    date_labels = "%b-%Y",
    breaks = br
  ) +
  scale_y_continuous(labels = scales::label_number()) +
  theme_bde()
```
