---
title: "Series index"
date: "`r Sys.Date()`"
description: A summary of all the information accessible with tidyBdE
toc: true
tbl-cap-location: bottom
knitr:
  opts_chunk:
    collapse: true
    comment: '#>'
    warning: false
    message: false
    tidy: "styler"
    dev: "ragg_png"
    dpi: 300
    out.width: "100%"
---

The following table shows the series available in the catalog (Last update:
**`r format(Sys.Date(),"%d-%B-%Y")`**).

Use the sequential number below to load a single series (see
[Example](#example)):

## Summary

```{r}
#| label: reactable
#| echo: false
library(tidyBdE)
library(ggplot2)
library(dplyr)
library(tidyr)

series <- bde_catalog_load()

# Clean
series_clean <- series |>
  filter(!is.na(Numero_secuencial)) |>
  select(
    Numero_secuencial,
    Descripcion_de_la_serie,
    Titulo_de_la_serie,
    Tipo_de_variable,
    Fecha_de_la_primera_observacion,
    Fecha_de_la_ultima_observacion,
    Frecuencia_de_la_serie,
    Fuente
  ) |>
  as_tibble()

library(reactable)

reactable(
  series_clean,
  filterable = TRUE,
  searchable = TRUE,
  resizable = TRUE,
  showPageSizeOptions = TRUE,
  striped = TRUE,
  defaultColDef = colDef(
    minWidth = 200,
    html = TRUE,
    align = "left",
    vAlign = "center"
  ),
  paginationType = "jump",
  defaultPageSize = 5,
  compact = TRUE,
  elementId = "bde-series"
)
```

## Example {#example}

For searching and extracting a specific series, see the full workflow:

```{r}
#| label: tbl-example
#| tbl-cap: Search results
library(tidyBdE)
library(tidyverse)

# GDP France
fr <- bde_catalog_search("Francia(.*)PIB")

# Show table on vignette
fr |>
  select(Numero_secuencial, Descripcion_de_la_serie) |>
  knitr::kable()
```

```{r}
#| label: tbl-meta
#| tbl-cap: Metadata of the indicator
# In this case we want to extract the first series
# See tidyverse style
fr |>
  # Select id
  select(Numero_secuencial) |>
  # first observation
  slice(1) |>
  # convert to numeric
  as.double() |>
  # And load it
  bde_series_load()

# See the metadata
fr |>
  # Select id
  select(Numero_secuencial) |>
  # first observation
  slice(1) |>
  # convert to numeric
  as.double() |>
  # And load the metadata
  bde_series_load(extract_metadata = TRUE) |>
  # To table on the vignette
  knitr::kable()
```
