---
title: "Series Index"
date: "`r Sys.Date()`"
---

```{r message=FALSE, warning=FALSE, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  tidy = "styler",
  comment = "#>",
  warning = FALSE,
  message = FALSE,
  dev = "ragg_png",
  dpi = 300,
  out.width = "100%"
)
```

The following table shows the series available on the catalog (Last update:
**`r format(Sys.Date(),"%d-%B-%Y")`**).

```{r set_locale, warning=FALSE, comment=FALSE, include=FALSE}
# Set locale in Spanish so accents and special characters shows up
# This is useful with GHA if running on windows

Sys.setlocale(category = "LC_ALL", locale = "Spanish")
```

Use the sequential number to load a single series (see [Example](#example)
below):

## Series index

```{r reactable, echo=FALSE, warning = FALSE, message=FALSE}
library(tidyBdE)
library(tidyverse)

series <- bde_catalog_load()


# Clean
series_clean <- series %>%
  filter(!is.na(Numero_secuencial)) %>%
  select(
    Numero_secuencial, Descripcion_de_la_serie,
    Titulo_de_la_serie,
    Fecha_de_la_ultima_observacion
  )


library(reactable)


reactable(series_clean,
  filterable = TRUE,
  searchable = TRUE,
  showPageSizeOptions = TRUE,
  striped = TRUE,
  paginationType = "jump",
  defaultPageSize = 5,
  compact = TRUE,
  elementId = "bde-series"
)
```

## Example {#example}

For searching and extracting a specific serie, see the full workflow:

```{r example}
library(tidyBdE)
library(tidyverse)

# GDP France
fr <- bde_catalog_search("Francia(.*)PIB")

# Show table on vignette
fr %>%
  select(Numero_secuencial, Descripcion_de_la_serie) %>%
  knitr::kable()

# In this case we want to extract the first serie
# See tidyverse style

fr %>%
  # Select id
  select(Numero_secuencial) %>%
  # of first obs
  slice(1) %>%
  # convert to number
  as.double() %>%
  # And load it
  bde_series_load()

# See the metadata
fr %>%
  # Select id
  select(Numero_secuencial) %>%
  # of first obs
  slice(1) %>%
  # convert to number
  as.double() %>%
  # And load the metadata
  bde_series_load(extract_metadata = TRUE) %>%
  # To table on the vignette
  knitr::kable()
```
