---
title: "Series Index"
---

```{r message=FALSE, warning=FALSE, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

if (isFALSE(requireNamespace("reactable", quietly = TRUE))) {
  install.packages("reactable")
}
```

The following table shows the series available on the catalog (Last update: 
**`r format(Sys.Date(),"%d-%B-%Y")`**).

Use the sequential number to load a single series (see [Example](#example) 
below):

```{r setup, echo=FALSE, warning = FALSE, message=FALSE}


library(tidyBdE)
library(tidyverse)

series <- bde_catalog_load()


# Clean
series_clean <- series %>%
  filter(!is.na(Numero_secuencial)) %>%
  select(
    Numero_secuencial, Descripcion_de_la_serie,
    Titulo_de_la_serie,
    Fecha_de_la_ultima_observacion
  )


library(reactable)


reactable(series_clean,
  filterable = TRUE,
  searchable = TRUE,
  showPageSizeOptions = TRUE,
  striped = TRUE,
  paginationType = "jump",
  defaultPageSize = 5,
  compact = TRUE
)
```

<h2 id="example">Example</h2>

For loading a single series (i.e. `2357793`) run the following code:

```{r example}

library(tidyBdE)

# Unemployment_Rate
series_example <- bde_series_load(2357793, "Unemployment Rate")


# Visualize
series_example
```
